---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates for Debian
    tags: always
    ansible.builtin.apt:
      update_cache: yes
      only_upgrade: yes
      auto_remove: yes
    when: ansible_distribution == "Debian"
