---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates for Debian
    tags: always
    ansible.builtin.apt:
      update_cache: yes
      install_recommends: yes
      force_apt_get: yes
      upgrade: dist
      autoclean: yes
      autoremove: yes
    when: ansible_distribution == "Debian"

    
- name: Check if a reboot is needed on all servers
   register: reboot_required_file
   stat:
     path: /var/run/reboot-required
     get_md5: no
