---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates for Debian
    tags: always
    ansible.builtin.apt:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Debian"
