---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates for Debian
    tags: always
    ansible.builtin.apt:
      update_cache: yes
      install_recommends: yes
      upgrade: "*"
      autoclean: yes
      autoremove: yes
    when: ansible_distribution == "Debian"
